language: node_js
node_js:
  - "8"
before_install:
  - npm i -g npm@3

# Encrypted secrets
env:
  - secure: "Q05YEC2BAwhlcOYoLQOAniomXafy/SZdjc44/NdwC5qxuMakG/ARWSHM/6Ntl8IEEIWQlukXoE5ab5MFdrsmLypMqfxxAB6He5u2gI7qnqNlZdq+lBFsYjO+qC53E+jYptNc1MjDkBT068ZCSuoA1uPAd1PlWs+7iDAt5z6zEEfIMxhzxJ0SYLZeON4HDbb7gHSoO8CN3bUwas0tjtKPCkzjFbMYbdONj5zPs/gv2mOejMuewwiHGdKSC2EMQhe+TiDBKh4/3cWwVDvJXSVWkQDFRUPsYT+1DuLFZTpaxyURGwWYVVy81Yv4Q7XS30EX7gepqL7daoKEM5vUcNBUhBwsw8iK3tOHDv4Io9ody7+agxBN6aQijE7hwms2cBZnIjk5eElv2/XkXSolHqliTy+pUrSRXAXUXBkzj1z+D69RIxFKJ9iCioAs966lDav+rN345H0FAIRuBhfE16PFnBlX/CroJuQ+Jl/wwkoJi+9V6pTQhO3toMIHg8Cf9MIKXr8Xn+L0drT7mplEtfA0GuyinLcPwX8DYdKe3m2ipCVk4+d2Gj4TPAZ1sUxQ00muQnuRmlf5Vwt6U1chOmC4hR1AHeyHELECeu4taC0Ri0dSt8vfxFIuk0W27P2ZsZeoNE5BpT0WWsiOCias0Q1tVWW2h8DLBcjda8pXuWIMBJM="
  - secure: "iau8fzuYzPr31JUISYXL+fFrhsZQTIPo6J1noM7PdJhxTF4BFoYMxda5ZdjpHkcSys0KPUxeZyj9r7R9agZBYTJPSBGq+XxaawrlFgMuiL3fWU0l/2AVweGD1dBLSyvxltynZJxdWLNq2KUgS5R/Y6YizkFeQxas76FRj/FFwKFyFdZHHJhyY5OSatKu3zN4G9DKlVxx//ONcapajAz2/queZc5rkb4ZlzYNfpnYOvNQoKbLMDRc6YMdh99wL+f80cX7zaPtcT/Je8O9sYCfc9Iymmg94zS4N0MXSSqBOOstsO5GyWEnzACwdCVkT6hzcJYIUhgSaaLx4XamNIR2KuuKCxvArWJEJ4C/sqeTTp+YgIXLZ9MeF/f9Yt8SxgKDbbnczi52F76RuiewJojoYtPjlmV8GZvMXiLfMkXWJRXdBvoQJbFbbawg5mbz2heQU+Odl4y5QNGEU2SAbUhRxH146EGPb3Ptts/Rl31jolRfOUBKFa7cm/fVgvylfWw0b11pQHs5pLZtYBeqacLotjZ5dcr0phdsO7+SNh2GlrfkxphYbdKDhYbtZuDinrLmJeko1e1RdP9t17YGe4JyarOXWcx5DxnnSshA/RiE6g9e+f0IR4Q8Ne9yWF+EpsRCGDr0/3tNWB0v8OmlxbZBzA7xe/d5R7or1DQ2U91YV8M="

# Deploy to dev on pushes to dev-deploy
deploy:
  provider: script
  script: dev-deploy.sh
  on:
    branch: dev-deploy
# Deploy to prod on pushes to prod-deploy
deploy:
  provider: script
  script: prod-deploy.sh
  on:
    branch: prod-deploy
