//ActionTypes.js

//LoginManagement actions
export const LOGIN_MNGMNT = {
  CHANGE_EMAIL: 'CHANGE_EMAIL',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  SET_ERROR: 'SET_ERROR',
  GOTO_USER_FORM : 'GOTO_USER_FORM',
  LOGIN: 'LOGIN',
  LOGIN_POST_FETCH: 'LOGIN_POST_FETCH',
  MLH: 'MLH',
  RETRIEVE_PASSWORD: 'RETRIEVE_PASSWORD',
  SIGNUP: 'SIGNUP'
};
