//ActionTypes.js

//LoginManager actions
export const LOGIN_MNGMNT = {
  CHANGE_EMAIL: 'CHANGE_EMAIL',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  SET_ERROR: 'SET_ERROR',
  SET_LOGIN_STATUS: 'SET_LOGIN_STATUS',
  SET_MAGIC_LINK: 'SET_MAGIC_LINK',
  HAS_FORGOTTEN_PASSWORD: 'HAS_FORGOTTEN_PASSWORD'
};

//UserManager actions
export const USER_DATA = {
  SET_EMAIL: 'SET_EMAIL',
  SET_TOKEN: 'SET_TOKEN',
  SET_RESUME: 'SET_RESUME',
  SET_USER_INFO: 'SET_USER_INFO',
  SET_MENTOR_INFO: 'SET_MENTOR_INFO',
  SET_COC: 'SET_COC',
  SET_SHARE: 'SET_SHARE',
  SET_QR: 'SET_QR',
  SET_FLASH: 'SET_FLASH'
};
