# You might ask why this workflow exists? Well apparently, the linter can pass but the build can still fail. So at some point during the review process we need to run the build. Hence, this file

name: Code Build Assurance

on:
    pull_request:
        branches: [env/dev]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                node-version: [12.x, 14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Test using Node ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: NODE_ENV=development CI=false npm run build-dev
